development:
  adapter: postgresql
  database: development
  pool: 2
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  user: <%= ENV['USER'] %>
  password: <%= ENV['PASS'] %>
  database: production
